Acme\TestBundle\Entity\Books:
    type: entity
    table: books
    indexes:
        idx_4a1b2a92679e91b3:
            columns:
                - writter_id
        fki_rating_id_fkey:
            columns:
                - rating_id
        fki_thread_id_fkey:
            columns:
                - thread_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        isbn:
            type: string
            nullable: true
            length: 64
            fixed: false
            comment: ''
        pageNumber:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: page_number
        cases:
            type: integerarray
            nullable: true
            comment: ''
    manyToOne:
        writter:
            targetEntity: Writers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                writter_id:
                    referencedColumnName: id
            orphanRemoval: false
        thread:
            targetEntity: Thread
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                thread_id:
                    referencedColumnName: id
            orphanRemoval: false
        rating:
            targetEntity: Rating
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rating_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        readlist:
            targetEntity: Readlists
            cascade: {  }
            mappedBy: null
            inversedBy: book
            joinTable:
                name: readlist_books
                joinColumns:
                    -
                        name: book_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: readlist_id
                        referencedColumnName: id
            orderBy: null
        category:
            targetEntity: Categories
            cascade: {  }
            mappedBy: book
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
