Acme\TestBundle\Entity\Books:
    type: entity
    table: books
    indexes:
        idx_4a1b2a92a32efc6:
            columns:
                - rating_id
        idx_4a1b2a92e2904019:
            columns:
                - thread_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        isbn:
            type: string
            nullable: true
            length: 64
            fixed: false
            comment: ''
        filepath:
            type: string
            nullable: true
            length: 128
            fixed: false
            comment: ''
        pageNumber:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: page_number
        created:
            type: datetime
            nullable: false
            comment: ''
        updated:
            type: datetime
            nullable: false
            comment: ''
    manyToOne:
        thread:
            targetEntity: Thread
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                thread_id:
                    referencedColumnName: id
            orphanRemoval: false
        rating:
            targetEntity: Rating
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rating_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        writer:
            targetEntity: Writers
            cascade: {  }
            mappedBy: null
            inversedBy: book
            joinTable:
                name: books_writers
                joinColumns:
                    -
                        name: book_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: writer_id
                        referencedColumnName: id
            orderBy: null
        category:
            targetEntity: Categories
            cascade: {  }
            mappedBy: null
            inversedBy: book
            joinTable:
                name: books_categories
                joinColumns:
                    -
                        name: book_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: category_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
