Acme\TestBundle\Entity\Readlists:
    type: entity
    table: readlists
    indexes:
        idx_d0f73387a76ed395:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 1024
            fixed: false
            comment: ''
        color:
            type: string
            nullable: true
            length: 6
            fixed: false
            comment: ''
        type:
            type: string
            nullable: true
            length: null
            fixed: false
            comment: ''
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        book:
            targetEntity: Books
            cascade: {  }
            mappedBy: readlist
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
