Acme\TestBundle\Entity\Thread:
    type: entity
    table: thread
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        permalink:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        isCommentable:
            type: boolean
            nullable: false
            comment: ''
            column: is_commentable
        numComments:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: num_comments
        lastCommentAt:
            type: datetime
            nullable: true
            comment: ''
            column: last_comment_at
    lifecycleCallbacks: {  }
