Acme\TestBundle\Entity\Users:
    type: entity
    table: users
    uniqueConstraints:
        uniq_1483a5e9a0d96fbf:
            columns:
                - email_canonical
        uniq_1483a5e992fc23a8:
            columns:
                - username_canonical
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        usernameCanonical:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: username_canonical
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        emailCanonical:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: email_canonical
        enabled:
            type: boolean
            nullable: false
            comment: ''
        salt:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        lastLogin:
            type: datetime
            nullable: true
            comment: ''
            column: last_login
        locked:
            type: boolean
            nullable: false
            comment: ''
        expired:
            type: boolean
            nullable: false
            comment: ''
        expiresAt:
            type: datetime
            nullable: true
            comment: ''
            column: expires_at
        confirmationToken:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            comment: ''
            column: password_requested_at
        roles:
            type: array
            nullable: false
            length: null
            fixed: false
            comment: ''
        credentialsExpired:
            type: boolean
            nullable: false
            comment: ''
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            nullable: true
            comment: ''
            column: credentials_expire_at
        firstname:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        middlename:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        lastname:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        avatar:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        phone:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
