Acme\TestBundle\Entity\Writers:
    type: entity
    table: writers
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        firstName:
            type: string
            nullable: true
            length: 256
            fixed: false
            comment: ''
            column: first_name
        middleName:
            type: string
            nullable: true
            length: 256
            fixed: false
            comment: ''
            column: middle_name
        lastName:
            type: string
            nullable: true
            length: 256
            fixed: false
            comment: ''
            column: last_name
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        filepath:
            type: string
            nullable: true
            length: 256
            fixed: false
            comment: ''
    manyToMany:
        book:
            targetEntity: Books
            cascade: {  }
            mappedBy: writer
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
