# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            tsvector: Library\CatalogBundle\DBAL\Types\TsvectorType
            integer[]: Ajgl\Doctrine\DBAL\Types\IntegerArrayType
            readlist_type: Library\CatalogBundle\DBAL\Types\ReadlistEnumType
        mapping_types:
            tsvector: tsvector
            enum: string
            readlist_type: readlist_type
            _int4: integer[]
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            string_functions:
                TSQUERY: Library\CatalogBundle\DQL\TsqueryFunction
                TSRANK: Library\CatalogBundle\DQL\TsrankFunction
                TOTSVECTOR: Library\CatalogBundle\DQL\ToTsvector

doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations