Library\CatalogBundle\Entity\Books:
    type: entity
    repositoryClass: Library\CatalogBundle\Repository\BookRepository
    table: books
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        isbn:
            type: string
            nullable: true
            length: 64
            fixed: false
            comment: ''
            column: ISBN
        filepath:
            type: string
            nullable: true
            length: 128
            fixed: false
            comment: ''
            column: filepath
        pageNumber:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: page_number
        created:
            type: datetime
        updated:
            type: datetime
    oneToMany:
        reviews:
            targetEntity: Reviews
            mappedBy: book
            joinColumn:
                name: book_id
    manyToOne:
        thread:
            targetEntity: Library\CommentBundle\Entity\Thread
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                thread_id:
                    referencedColumnName: id
            orphanRemoval: false
        rating:
            targetEntity: Library\VotesBundle\Entity\Rating
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rating_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        writers:
            targetEntity: Writers
            cascade: {  }
            mappedBy: null
            inversedBy: book
            joinTable:
                name: books_writers
                joinColumns:
                   -
                       name: book_id
                       referencedColumnName: id
                inverseJoinColumns:
                   -
                       name: writer_id
                       referencedColumnName: id
            orderBy: null
        categories:
            targetEntity: Categories
            cascade: {  }
            mappedBy: null
            inversedBy: book
            joinTable:
                name: books_categories
                joinColumns:
                   -
                       name: book_id
                       referencedColumnName: id
                inverseJoinColumns:
                   -
                       name: category_id
                       referencedColumnName: id
            orderBy: null
        readlists:
            targetEntity: Readlists
            cascade: {  }
            mappedBy: null
            inversedBy: book
            joinTable:
                name: readlist_books
                joinColumns:
                    -
                        name: book_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: readlist_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks:
        prePersist: [updateTimestamps]
        preUpdate: [updateTimestamps]
