library\CatalogBundle\Entity\Book:
    type: entity
    table: books
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        description:
            type: text
            nullable: true

    manyToOne:
       category:
            targetEntity: library\CatalogBundle\Entity\Category
            cascade: {  }
            inversedBy: book
            joinTable:
                name: categories
                joinColumn:
                    -
                        name: category_id
                        referencedColumnName: id


    lifecycleCallbacks: {  }
