Library\CatalogBundle\Entity\Readlists:
    type: entity
    table: readlists
#    repositoryClass: Library\CatalogBundle\Repository\ReadlistsRepository
    indexes:
        idx_d0f73387a76ed395:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 1024
            fixed: false
            comment: ''
        color:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        type:
            type: readlist_type
            nullable: true
            comment: ''
    manyToOne:
        user:
            targetEntity: Library\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: "CASCADE"
            orphanRemoval: false
    oneToMany:
        books:
            targetEntity: ReadlistsBooks
            cascade: {  }
            mappedBy: readlist
    lifecycleCallbacks: {  }
