fos_comment:
    db_driver: orm
    class:
        model:
            comment: \Library\CommentBundle\Entity\Comment
            thread: \Library\CommentBundle\Entity\Thread

assetic:
    bundles: [ "FOSCommentBundle" ]