fos_user:
    db_driver: orm
    firewall_name: admin
    user_class: Library\UserBundle\Entity\User
    from_email:
        address:        noreply@noexist.com
        sender_name:    Mail Service
    registration:
        confirmation:
            enabled:    true
            from_email:
                address:        info@elib.tld
                sender_name:    Mail-bot
        form:
            type:  fos_user_rest_registration
            validation_groups:  [LibraryRegistration]
    profile:
        form:
            validation_groups: [LibraryProfile]
