library\UserBundle\Entity\User:
    type:  entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
            firstname:
                type: string
                length: '30'
                nullable: true
            middlename:
                type: string
                length: '30'
                nullable: true
            lastname:
                type: string
                length: '30'
                nullable: true
            avatar:
                type: string
                length: '255'
                nullable: true
            phone:
                type: string
                length: '50'
                nullable: true

    lifecycleCallbacks: {  }