dcs_rating:
    db_driver: orm
    base_path_to_redirect: / # when the permalink is not configured
    max_value: 5 # maximum value for the vote (stars displayed)
    model:
        rating: Library\VotesBundle\Entity\Rating
        vote: Library\VotesBundle\Entity\Vote