acme_test:
    resource: "@AcmeTestBundle/Resources/config/routing.yml"
    prefix:   /

library_votes:
    resource: "@LibraryVotesBundle/Resources/config/routing.yml"
    prefix:   /

catalog:
    resource: "@CatalogBundle/Resources/config/routing.yml"
    type : rest
    prefix:   /api/v1/

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    type : rest
    prefix:   /api/v1/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc


fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }