catalog:
    resource: "@CatalogBundle/Resources/config/routing.yml"
    prefix: /api/v1/

library_votes:
    resource: "@LibraryVotesBundle/Resources/config/routing.yml"
    prefix:   /api/v1/

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    type : rest
    prefix:   /api/v1/

# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc


fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

vkontakte_login:
    pattern: /login/check-vkontakte

logout:
    path: /logout
fos_user_oauth_wsse_bridge:
    pattern: /oauth/bridge
    defaults: {_controller: UserBundle:OAuthBridgeWSSE:bridge}
