catalog_readlists_api_v1:
    resource: "@CatalogBundle/Controller/ReadlistsRESTController.php"
    type:   rest
    prefix:   /api/v1

catalog_writers_api_v1:
    resource: "@CatalogBundle/Controller/WritersRESTController.php"
    type:   rest
    prefix:   /api/v1

catalog_reviews_api_v1:
    resource: "@CatalogBundle/Controller/ReviewsRESTController.php"
    type:   rest
    prefix:   /api/v1

catalog_books_api_v1:
    resource: "@CatalogBundle/Controller/BooksRESTController.php"
    type:   rest
    prefix:   /api/v1


catalog_categories_api_v1:
    resource: "@CatalogBundle/Controller/CategoriesRESTController.php"
    type:   rest
    prefix:   /api/v1

#acme_test:
#    resource: "@AcmeTestBundle/Resources/config/routing.yml"
#    prefix:   /

library_votes:
    resource: "@LibraryVotesBundle/Resources/config/routing.yml"
    prefix:   /


user:
    resource: "@UserBundle/Resources/config/routing.yml"
    type : rest
    prefix:   /api/v1/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc


fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
