# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
            dev:
                pattern:  ^/(_(profiler|wdt)|css|images|js)/
                security: false
            login:
                pattern:  ^/api/*.+users.*
                context:      user
                anonymous:    true
            token:
                pattern:  ^/api/*.+tokens.*
                context:      user
                anonymous:    true
            wsse_secured:
                pattern:      ^/api/.*
                context:      user
                stateless:    true
                wsse:
                    nonce_dir: null
                    provider: fos_userbundle
                    lifetime: 600
                anonymous:    false


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }