hwi_oauth:
    connect:
        account_connector: library_user_provider
    firewall_name: secured_area
    connect:
        confirmation: false
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
            vkontakte: vkontakte_id
    resource_owners:
        facebook:
            type:               facebook
            client_id:          264399430256345
            client_secret:      134b501ae1084fc4dd5608eb685f721c
            scope:              "email"
            paths:
                realname: ["first_name", "last_name", "middle_name"]
        vkontakte:
            type:                vkontakte
            client_id:           4899856
            client_secret:       5Sqwi71uVM99Q3TPGfBt
            scope:               "email"
            paths:
                realname:  ["response.0.first_name", "response.0.last_name", "response.0.nickname"]