services:
    vich_image.listener.image_removed:
        class:      Library\CatalogBundle\EventListener\ImageDelete
        arguments:  [ @logger, @liip_imagine.cache.manager, @vich_uploader.storage]
        tags:
            - { name: kernel.event_listener, event: vich_uploader.post_remove, method: onImageRemoved }