catalog_books_api_v1:
    type: rest
    resource: "@CatalogBundle/Controller/BooksRESTController.php"

catalog_categories_api_v1:
    type: rest
    resource: "@CatalogBundle/Controller/CategoriesRESTController.php"

catalog_writers_api_v1:
    type: rest
    resource: "@CatalogBundle/Controller/WritersRESTController.php"

catalog_readlists_api_v1:
    type: rest
    resource: "@CatalogBundle/Controller/ReadlistsRESTController.php"

catalog_reviews_api_v1:
    type: rest
    resource: "@CatalogBundle/Controller/ReviewsRESTController.php"
