service_token:
    type: rest
    resource: "UserBundle:TokenRest"
    name_prefix:  api_


user_user_api_v1:
    resource: "@UserBundle/Controller/UserRESTController.php"
    type:   rest


#fos_user_old_reg:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
fos_user_old_sec:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /register

fos_user_register:
    type: rest
    resource: "UserBundle:RegisterUserREST"
    name_prefix:  api_
    methods: [ POST ]
