login :
  type: rest
  resource: "UserBundle:Auth"
  name_prefix:  api_

service_token:
    type: rest
    resource: "UserBundle:TokenRest"
    name_prefix:  api_

service_user:
    type: rest
    resource: "UserBundle:UserRest"
    name_prefix:  api_

service_user_role:
    type: rest
    parent: service_user
    resource: "UserBundle:UserRoleRest"
