services:
    library.registration.form.type:
        class: Library\UserBundle\Form\RestRegistrationType
        arguments: ["Library\UserBundle\Entity\User"]
        tags:
            - { name: form.type, alias: fos_user_rest_registration }