Library\UserBundle\Entity\User:
    properties:
    # Your custom fields in your user entity, here is an example of fullName
#        fullName:
#            - NotBlank:
#                message: library_user.first_name.blank
#                groups: [ "LibraryProfile" ]
#            - Length:
#                min: 2
#                minMessage: library_user.first_name.short
#                max: 255
#                maxMessage: library_user.first_name.long
#                groups: [ "LibraryProfile" ]



# Note: We still want to validate the email
# See FOSUserBundle/Resources/config/validation/orm.xml to understand
# the UniqueEntity constraint that was originally applied to both
# username and email fields
#
# As you can see, we are only applying the UniqueEntity constraint to 
# the email field and not the username field.
FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
             fields: email
             errorPath: email 
             message: fos_user.email.already_used
             groups: [ "LibraryRegistration", "LibraryProfile" ]

    properties:
        email:
            - NotBlank:
                message: should not be empty
                groups: [ "LibraryRegistration", "LibraryProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "LibraryRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "LibraryRegistration", "LibraryProfile" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "LibraryRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                minMessage: fos_user.password.blank
                groups: [ "LibraryRegistration", "LibraryProfile", "ResetPassword", "ChangePassword"]

FOS\UserBundle\Model\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "LibraryRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "LibraryRegistration" ]

FOS\UserBundle\Propel\User:
    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "LibraryRegistration", "LibraryProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "LibraryRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "LibraryRegistration", "LibraryProfile" ]

        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "LibraryRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                minMessage: fos_user.password.blank
                groups: [ "LibraryRegistration", "LibraryProfile", "ResetPassword", "ChangePassword"]


FOS\UserBundle\Propel\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "LibraryRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "LibraryRegistration" ]