FOS\UserBundle\Model\User:
    exclusion_policy: NONE
    properties:
      avatar:
        groups: ["user"]
      email:
        groups: ["user"]

      password:
        exclude: true
      salt:
        exclude: true
      credentialsExpired:
        exclude: true
      enabled:
        exclude: true
      credentials_expired:
        exclude: true
      emailCanonical:
        exclude: true
      usernameCanonical:
        exclude: true
      facebook_id:
        exclude: true
      vkontacte_id:
        exclude: true
      vkontacte_access_token:
        exclude: true
      facebook_access_token:
        exclude: true
